// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF_C0ZtTcvo0TjfUb3R0iO6zPbwPI4SMk',
    appId: '1:473947018592:web:5e998a0970085f588fba05',
    messagingSenderId: '473947018592',
    projectId: 'social-media-app-f7197',
    authDomain: 'social-media-app-f7197.firebaseapp.com',
    storageBucket: 'social-media-app-f7197.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcn8Ecn4N5XrrzgJ8pvtX9xwCLglP1I6w',
    appId: '1:473947018592:android:262ceb1191731b1c8fba05',
    messagingSenderId: '473947018592',
    projectId: 'social-media-app-f7197',
    storageBucket: 'social-media-app-f7197.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAtkEYjuQiwPkkTD_eLcVJnlVcBtJirsg',
    appId: '1:473947018592:ios:a6b0d243b471ffa78fba05',
    messagingSenderId: '473947018592',
    projectId: 'social-media-app-f7197',
    storageBucket: 'social-media-app-f7197.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
